import "ol3-draw/tests/index";
import "ol3-fun/tests/index";
import "ol3-grid/tests/index";
import "ol3-input/tests/index";
import "ol3-layerswitcher/tests/index";
import "ol3-panzoom/tests/index";
import "ol3-popup/tests/index";
import "ol3-search/tests/index";
import "ol3-symbolizer/tests/index";
